# Generated by Django 5.2.6 on 2025-11-20 18:48

import django.utils.timezone
import hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datphong',
            fields=[
                ('madatphong', models.AutoField(primary_key=True, serialize=False)),
                ('ngaydat', models.DateTimeField(db_column='ngaydat', default=django.utils.timezone.now)),
                ('ngaynhan', models.DateField(blank=True, null=True)),
                ('ngaytra', models.DateField(blank=True, null=True)),
                ('trangthai', models.CharField(blank=True, choices=[('dangcho', 'Đang chờ'), ('xacnhan', 'Đã xác nhận'), ('huy', 'Đã hủy'), ('hoanthanh', 'Hoàn thành')], db_column='trangthai', default='dangcho', max_length=20, null=True)),
                ('phuongthucthanhtoan_du_kien', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'datphong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dichvu',
            fields=[
                ('madichvu', models.AutoField(primary_key=True, serialize=False)),
                ('tendichvu', models.TextField(blank=True, null=True)),
                ('mota', models.TextField(blank=True, null=True)),
                ('gia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'dichvu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hoadon',
            fields=[
                ('mahoadon', models.AutoField(primary_key=True, serialize=False)),
                ('ngayphathanh', models.DateField(blank=True, null=True)),
                ('tienphong', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tiendichvu', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tongtien', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trangthai', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hoadon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('makhachhang', models.AutoField(primary_key=True, serialize=False)),
                ('tenkhachhang', models.TextField(blank=True, null=True)),
                ('cccd', models.TextField(blank=True, null=True, unique=True)),
                ('sdt', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('diachi', models.TextField(blank=True, null=True)),
                ('ngaysinh', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'khachhang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loaiphong',
            fields=[
                ('maloaiphong', models.AutoField(primary_key=True, serialize=False)),
                ('tenloaiphong', models.TextField(blank=True, null=True)),
                ('mota', models.TextField(blank=True, null=True)),
                ('gia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'loaiphong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nhanvien',
            fields=[
                ('manhanvien', models.AutoField(primary_key=True, serialize=False)),
                ('hoten', models.TextField(blank=True, null=True)),
                ('sdt', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('chucvu', models.TextField(blank=True, null=True)),
                ('luong', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ngayvaolam', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nhanvien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('maphong', models.AutoField(primary_key=True, serialize=False)),
                ('sophong', models.TextField(blank=True, null=True)),
                ('trangthai', models.TextField(blank=True, null=True)),
                ('anh', models.FileField(blank=True, db_column='anh', null=True, upload_to=hotel.models.room_upload_path)),
            ],
            options={
                'db_table': 'phong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sudungdichvu',
            fields=[
                ('masddv', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.IntegerField()),
                ('tongtien', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'sudungdichvu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taikhoan',
            fields=[
                ('mataikhoan', models.AutoField(primary_key=True, serialize=False)),
                ('tentaikhoan', models.TextField(blank=True, null=True)),
                ('matkhau', models.TextField(blank=True, null=True)),
                ('vaitro', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taikhoan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaiKhoanKhachHang',
            fields=[
                ('mataikhoan', models.AutoField(db_column='mataikhoan', primary_key=True, serialize=False)),
                ('tentaikhoan', models.CharField(db_column='tentaikhoan', max_length=150, unique=True)),
                ('matkhau', models.CharField(db_column='matkhau', max_length=255)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'taikhoankhachhang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaiKhoanNhanVien',
            fields=[
                ('mataikhoan', models.AutoField(db_column='mataikhoan', primary_key=True, serialize=False)),
                ('tentaikhoan', models.CharField(db_column='tentaikhoan', max_length=150, unique=True)),
                ('matkhau', models.CharField(db_column='matkhau', max_length=255)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=255, null=True, unique=True)),
                ('vaitro', models.CharField(blank=True, db_column='vaitro', max_length=50, null=True)),
            ],
            options={
                'db_table': 'taikhoannhanvien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thanhtoan',
            fields=[
                ('mathanhtoan', models.AutoField(primary_key=True, serialize=False)),
                ('sotien', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hinhthucthanhtoan', models.TextField(blank=True, null=True)),
                ('thoigian', models.TimeField(blank=True, null=True)),
                ('trangthai', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'thanhtoan',
                'managed': False,
            },
        ),
    ]
